application: macgooblog
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /test.*
   #login: admin  # This is important if you deploy the test directory in production!
  script: lib/gaeunit.py

- url: /mapreduce(/.*)?
  login: admin
  script: google/appengine/ext/mapreduce/main.py

- url: .*
  script: main.py

skip_files:
- ^(.*/)?google/.*